name: Automatic-Speech-Recognition
dependencies:
  - python=3.7.5
  - tensorflow=2.0.0
  - pandas=0.25.3
  - pytables=3.6.1
  - pytest=5.3.2
  - testfixtures=6.10.3
  - pip:
    - python-speech-features==0.6
